# Generated by Django 5.1 on 2024-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15),
        ),
    ]
