# Generated by Django 5.1 on 2024-08-26 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_trade_trading_price_trade_trading_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='traded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 6, 3, 45, 55765), null=True),
        ),
    ]
