# Generated by Django 5.1 on 2024-08-26 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0008_alter_trade_traded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='traded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 7, 23, 13, 353182), null=True),
        ),
    ]
