# Generated by Django 5.1 on 2024-08-27 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0013_alter_trade_traded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='traded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 22, 49, 15, 969259), null=True),
        ),
    ]
