# Generated by Django 5.1 on 2024-08-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0017_alter_trade_traded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_reason',
            field=models.TextField(null=True),
        ),
    ]
