# Generated by Django 5.1 on 2024-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='created_at',
        ),
        migrations.AddField(
            model_name='market',
            name='market_date',
            field=models.DateField(null=True),
        ),
    ]
