# Generated by Django 5.1 on 2024-08-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_remove_market_created_at_market_market_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
